-- Exercise 2: Dvdrental Database
-- 1.
-- -- SELECT * FROM customer;
-- 2.
-- -- SELECT (first_name ||' '|| last_name) AS full_name FROM customer;
-- 3.
-- -- SELECT DISTINCT create_date FROM customer;
-- 4.
-- -- SELECT * FROM customer ORDER BY first_name DESC;
-- 5.
-- SELECT film_id, title, description, release_year, rental_rate
-- FROM film ORDER BY rental_rate ASC;
-- 6.
-- SELECT address, phone FROM address WHERE district = 'Texas';
-- 7.
-- SELECT * FROM film WHERE film_id = 15 OR film_id = 150;
-- 8.
-- SELECT film_id, title, description, length, rental_rate FROM film
-- WHERE title = 'Toy Story';
-- 9.
-- SELECT film_id, title, description, length, rental_rate FROM film
-- WHERE title ILIKE 'To%';
-- 10.
-- SELECT * FROM film ORDER BY rental_rate ASC LIMIT 10;
-- 11.
-- SELECT * FROM film ORDER BY rental_rate ASC LIMIT 10 OFFSET 10;
-- 12.
-- SELECT customer.first_name, customer.last_name, payment.amount, payment.payment_date
-- FROM customer LEFT OUTER JOIN payment
-- ON customer.customer_id = payment.customer_id ORDER BY customer.customer_id ASC;
-- 13.
-- SELECT film.film_id, film.title FROM film
-- LEFT OUTER JOIN inventory ON film.film_id = inventory.film_id
-- WHERE film.film_id NOT IN (SELECT inventory.film_id FROM inventory);
-- 14.
-- SELECT city.city, country.country FROM city INNER JOIN country
-- ON city.country_id = country.country_id;
